### ISSUE TITLE
Allow wiki links in structured data and comments

### ISSUE THREAD

**Issue by madsbuch** [obsidianmd/forum-theme#1]
Obsidian is great, love the graph view! However, I have some files that are written to be publicized eventually, and I don't want internal links in those files (I use Pandoc to make PDFs).

Two ways ti mitigate this can be:
1. Allow wiki links in comments
2. Allow wiki links in the structured data part of the files

What are your thoughts?

(Sry for writing here, seemed to be the easiest channel not wanting to setup accounts on discord or your forum)

**Comment by ericaxu** [comment]
@madsbuch You can use normal Markdown links to link to the actual Markdown files, e.g. `[Link text](../markdown-file.md)`, those will work and do show up in the graph view and backlinks.

It's just that autocomplete won't work, and you need to replace spaces with `%20` to make the URL compliant.

Hope that helps!

**Comment by ericaxu** [comment]
> (Sry for writing here, seemed to be the easiest channel not wanting to setup accounts on discord or your forum)

I agree it's an easy channel for developers, but since it's not official, I didn't even realize there was an issue until a moderator notified us. Although it's a bit of work to set up a forum account, I think in the long run that's better for everyone: (1) with limited resources (just the two of us doing development) we can see things in centralized places, and (2) existing knowledge can be searched and referred to.

To demonstrate (2), you can actually find what (I believe) you're looking for in the forum with a bit of search:

[Obsidian Release v0.6.6](https://forum.obsidian.md/t/obsidian-release-v0-6-6/1167) (No.3 under "Changes")
[Support real Markdown links between notes](https://forum.obsidian.md/t/support-real-markdown-links-between-notes/231)

So after closing this issue, we'll close the Issues section for our repos. Hope that's understandable.

**Comment by madsbuch** [comment]
@ericaxu thanks a lot! It makes complete sense (I was surprised that this section was open after all!) I do like your product and will join your discord!
